# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarTerrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bumpy', models.FloatField(max_length=10)),
                ('grade', models.FloatField(max_length=10)),
                ('speed', models.CharField(max_length=10)),
            ],
        ),
    ]
